#server
server.port=8082

spring.application.name=garmentDesign
#sql server
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=HoaTranmaymac;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#time
spring.jackson.time-zone=Asia/Ho_Chi_Minh

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoatranmaymac@gmail.com
spring.mail.password=gxyvxdzyrfzorwte
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true